---
- block:
  - name: Disable repos
    ini_file:
      dest: /etc/yum.repos.d/CentOS-Base.repo
      section: "{{ item }}"
      option: enabled
      value: '0'
    with_items:
       - base
       - updates
       - extras

  - name: Add registry repo
    yum_repository:
      name: registry
      description: Registry local repo
      baseurl: https://{{ registry }}/repos/
      gpgcheck: no
      enabled: yes
      sslverify: no

  - name: yum-clean-metadata
    command: yum clean metadata
    args:
      warn: no

  - name: Install packages
    yum :
      name:
        - vim
        - nano
        - nmap-ncat
        - bind-utils
        - traceroute
        - mc
        - tree
      state: latest

  become: yes
