---
- block:

  - name: Install Postgresql server
    yum :
      name: 
        - postgresql96
        - postgresql96-server
        - postgresql96-contrib
      state: installed

  - name: Set owner and permission for /var/lib/pgsql/ 
    file:
      path: /var/lib/pgsql/      
      owner: postgres
      group: postgres
      mode: 0755
      state: directory

  - name: Make data dir /var/lib/pgsql/data for postgres
    file:
      path: /var/lib/pgsql/data
      owner: postgres
      group: postgres
      mode: 0700
      state: directory

  become: yes
